sim_dt: 0.001
control_dt: 0.025
obs_history_len: 1
action_smoothing: 0.5

# Path for exporting generated MuJoCo XML files
# If not set, defaults to /tmp/mjcf-export
xml_export_path: /tmp/mjcf-export

# default
# kp: [400, 400, 400, 600, 150, 150, 400, 400, 400, 600, 150, 150]
# kd: [40, 40, 40, 60, 15, 15, 40, 40, 40, 60, 15, 15]

kp: [400, 400, 400, 600, 150, 150, 400, 400, 400, 600, 150, 150]
kd: [40, 40, 40, 60, 15, 15, 40, 40, 40, 60, 15, 15]

arm_kp: [40, 30, 40, 30]
arm_kd: [4, 3, 4, 3]  

# Half-sitting pose in degrees
half_sitting_pose: [-30, 0, 0, 50, 0, -24,
                    -30, 0, 0, 50, 0, -24]

# Arm half-sitting pose in degrees
arm_half_sitting_pose: [20.0, -80.0, 20.0, -80.0]

# Task parameters
task:
  goal_height: 0.80
  total_duration: 1.0
  swing_duration: 0.7
  stance_duration: 0.3

# 0.80, 1.1, 0.75, 0.35